FROM nvidia/cuda:12.2.2-devel-ubuntu22.04 as cuda-pip-torch

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip \
    python3-dev && \
    rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --upgrade pip

RUN pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu123

RUN pip install diffusers transformers scipy accelerate
RUN pip install Flask Flask-Sockets

WORKDIR /app/server/

CMD python3 server.py
