FROM nvidia/cuda:12.1.1-devel-ubuntu22.04
RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip3 install --upgrade pip
RUN pip3 install "python-socketio[client]" eventlet
RUN pip install torch torchvision torchaudio
RUN pip install transformers
RUN pip install accelerate scipy
