FROM nvidia/cuda:12.2.2-devel-ubuntu22.04 as cuda-pip-torch

# Install python3 and pip3
RUN apt-get update && apt-get install -y python3 python3-pip

# Update pip3
RUN pip3 install --upgrade pip

RUN pip3 install "python-socketio[client]" eventlet

RUN pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu123
