FROM nvidia/cuda:11.4.3-base-ubuntu20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip3 install --upgrade pip
RUN pip install torch torchvision torchaudio

RUN pip install flask diffusers transformers scipy
RUN pip install accelerate peft

# ------------- for stable-diffusion-xl-base-1.0 -------------
# https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0
RUN pip install invisible_watermark transformers accelerate safetensors
RUN apt-get update && \
    apt-get install -y libgl1-mesa-glx && \
    rm -rf /var/lib/apt/lists/*
RUN apt-get update && \
    apt-get install -y libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*
# ------------- end section for stable-diffusion-base-1.0 -------------

WORKDIR /app
COPY . .
WORKDIR /app/server/

CMD python3 server.py
