# Dockerfile for running the doodle server (and serving the client code)
# Start with ubuntu 22.04
FROM ubuntu:22.04

# Install python3 and pip3
RUN apt-get update && apt-get install -y python3 python3-pip

WORKDIR /app

# Run http.server to serve the client code, which will be mounted to /app/client
# We have to specify the client directory in the command
CMD python3 -m http.server 8001 --directory /app/client
