from ubuntu:22.04

# Install python3 and pip3
RUN apt-get update && apt-get install -y python3 python3-pip

# Update pip3
RUN pip3 install --upgrade pip

RUN pip3 install "python-socketio[client]" eventlet
